version: '3.7'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - redis:/data

  arabot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arabot
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

volumes:
  postgres:
    name: arabot-db
  redis:
    name: arabot-redis
